In [88]:
import pandas as pd
import numpy as np

In [92]:
# np.random.seed(69)
names = np.random.choice(np.arange(65,90), size=10, replace=False)
names = np.array([chr(i) for i in names])
marks = np.random.randint(1,100,size=(10,10))

[[68 80 22 31 37 93 69 76 96 79]
 [33  9 36  6 23 86 74 61 51 48]
 [15 97  8 11 54 93 95 76  5 58]
 [16 90 70 28  7 84 30 87 41 41]
 [63 53 80 21 14 93 98 18 32 93]
 [81 32 22 18 19  6 91 37 25 69]
 [16 74 48 76 14 23 76 84  2 10]
 [86 96 53 97 30 74 76 21 65 27]
 [22 40 64 31 17 82 39 62 33 55]
 [58 86 57 33 38 33  8 78 46 29]]


In [93]:
# count = 0
# rows=[]
# for name in names:
#     rows.append([name,np.average(marks[count]),np.max(marks[count]),np.min(marks[count])])
#     count+=1
# data=np.array(rows)
# df = pd.DataFrame(data)
# print(df)

In [104]:
df = pd.DataFrame({
    'Names': names,
    'Marks': list(marks)
})

for i in df["Marks"]:
    print(i)
    marks = np.array([i])
#     print(marks)
#     print(np.average(marks),np.max(marks),np.min(marks))

ValueError: All arrays must be of the same length